### ISSUE TITLE
On-prem Sentry

### ISSUE THREAD

**Issue by lol768** [tclindner/sentry-releases-action#19]
Do you support configuring the URL to point at a custom Sentry instance?

**Comment by tclindner** [comment]
Hey @lol768 I haven't tried that before. This action wraps the sentry-cli, so I believe it should work. Can you please try setting [`SENTRY_URL`](https://docs.sentry.io/cli/configuration/#configuration-values) as an environment variable? 

If it works, we can add it to the docs. 🤞 ☘️

**Comment by tclindner** [comment]
Hey @lol768 did you have any luck with the `SENTRY_URL` environment variable?

**Comment by lol768** [comment]
Sorry @tclindner  - totally forgot to update this issue! Your actions been running as part of our CI workflow in prod for 17 days now, and the releases are created just great on our on-prem instance.

**Comment by tclindner** [comment]
That’s great news!

**Comment by tclindner** [comment]
Thank you for the PR!
