### ISSUE TITLE
Invalid repository name leads to authorization error

### ISSUE THREAD

**Issue by franky47** [tclindner/sentry-releases-action#35]
I'm trying to use this action, but it fails with [the following error](https://github.com/chiffre-io/chiffre/runs/421784583?check_suite_focus=true#step:9:14):
```
##[error]Command failed: /home/runner/work/_actions/tclindner/sentry-releases-action/v1.0.0/dist/sentry-cli releases set-commits bfd4135e51c9949feb732f4b12194dee3af5a2a9 --auto
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
```
I believe the issue comes from this line, where `repo` is hardcoded, and does not correspond to any repository integration on Sentry:
https://github.com/tclindner/sentry-releases-action/blob/992383a34f94af668c64166a73b96709a2635729/src/create-release.js#L26

**Comment by franky47** [comment]
Nevermind, I might have opened this issue too quickly, looks like the problem is somewhere else, the `auto` flag takes precedence.

**Comment by franky47** [comment]
The issue had to do with insufficient permissions (scopes) on the token I used for authenticating with the Sentry API, probably `org:read` was missing to list the repositories attached to the organization: `GET https://sentry.io/api/0/organizations/{org}/repos/?cursor=`.

**Comment by tclindner** [comment]
Thanks, @franky47. I'm glad you got it working! Thanks for documenting what you had to do. 👍
