### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ChrisLovering** [tclindner/sentry-releases-action#504]
Is there any chance a new release can be made for this repo to pull in all the changes since May 2020 (date of the last release)?

Notably 1.2.0 still uses node12, which causes [deprecation warnings](https://github.com/python-discord/bot/actions/runs/5877165800) when being ran. I can see on master this has been [bumped up to node 16](https://github.com/tclindner/sentry-releases-action/blob/master/package.json#L49), along with many other dependency bumps .

**Comment by pkarman** [comment]
Node16 is now also deprecated. Is this project still maintained?

**Comment by tclindner** [comment]
Hey @pkarman no I'm not actively maintaining this anymore. I'll cut a release. Would you mind coming a maintainer? Thanks!

**Comment by karpet** [comment]
@tclindner happy to.

**Comment by tclindner** [comment]
Awesome! What ID are you actively using? Your personal one in the second comment?

**Comment by pkarman** [comment]
> Awesome! What ID are you actively using? Your personal one in the second comment?

@pkarman

**Comment by pkarman** [comment]
sorry, if you meant npmjs id, it is karpet
