### ISSUE TITLE
Documentation question: What permissions does the API key need?

### ISSUE THREAD

**Issue by mlissner** [tclindner/sentry-releases-action#90]
Just working on getting this set up, and I can't find where the readme says what permissions are needed. Clarification would be great. Going to try giving just the releases permission, but I suspect iteration pain in my future. 

Thanks for the useful tool.

**Comment by mlissner** [comment]
Looks like you need `org:read` and `project:releases`, unless I'm missing something. I'll do a PR.

**Comment by tclindner** [comment]
Thank you! You are spot on. 🙌
